name: Publish Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  call-publish:
    uses: leoweyr/github-release-workflow/.github/workflows/reusable-publish-release.yml@develop
    with:
      npm-node-version: '20'
      npm-package-dir: '.'
      npm-deploy-command: 'npm run deploy'
      trb-repository: 'ODCLAB/odyssey-plan'
      trb-project-node-name: 'TODO Requirement Blueprint Engine'
    secrets:
      ACCESS_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
